
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Providers from "./providers";

const poppins = Poppins({
  weight: ['400', '700'], // Specify the weights you want to use
  subsets: ['latin'], // Specify the character sets you need
  display: 'swap', // Use 'swap' for optimal loading
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  );
}